spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./db/filmorate;DB_CLOSE_DELAY=-1
    username: sa
    password: p_h2-Db
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      platform: h2
      encoding: UTF-8
      separator: ";"
      continue-on-error: false

logging:
  level:
    org:
      springframework: ERROR
    ru:
      yandex:
        practicum:
          filmorate: TRACE