DB_CLOSE_DELAY: -1
logging:
  level:
    org:springframework: ERROR
    ru:yandex:practicum:filmorate: TRACE
spring:
  sql:init:
    mode: always
    continue-on-error: false
  jpa:hibernate:ddl-auto: none
  datasource:
    initialization-mode: always
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: p_h2-Db
    driverClassName: org.h2.Driver
