DB_CLOSE_DELAY: -1
logging:
  level:
    org:springframework: ERROR
    ru:yandex:practicum:filmorate: TRACE
spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: p_h2-Db
    driverClassName: org.h2.Driver
    h2:
      console:
        enable: true
        path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

  sql:
    init:
      mode: always
      platform: h2
      encoding: UTF-8
      separator: ;
      continue-on-error: false