logging: println!("Hello, world!");
  level:
    org:springframework: ERROR
    ru:yandex:practicum:filmorate: TRACE
spring:
  sql:init:
    mode: always
    continue-on-error: true
  datasource:
    initialization-mode: always
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password:
    driverClassName: org.h2.Driver
