CREATE TABLE IF NOT EXISTS GENRE (
  NAME CHARACTER VARYING(50) NOT NULL,
  CONSTRAINT GENRE_PK PRIMARY KEY (NAME)
);

CREATE TABLE IF NOT EXISTS RATING (
  NAME CHARACTER VARYING(50) NOT NULL,
  CONSTRAINT RATING_PK PRIMARY KEY (NAME)
);

CREATE TABLE IF NOT EXISTS STATUS (
  NAME CHARACTER VARYING(50) NOT NULL,
  CONSTRAINT STATUS_PK PRIMARY KEY (NAME)
);

CREATE TABLE IF NOT EXISTS FILM (
  FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME CHARACTER VARYING(50) NOT NULL,
  DESCRIPTION CHARACTER VARYING(200),
  RELEASE_DATE DATE,
  DURATION INTEGER,
  RATING_NAME CHARACTER VARYING(50),
  CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID)
);

CREATE TABLE IF NOT EXISTS PERSON (
  PERSON_ID BIGINT NOT NULL AUTO_INCREMENT,
  EMAIL CHARACTER VARYING(100) NOT NULL,
  LOGIN CHARACTER VARYING(50) NOT NULL,
  NAME CHARACTER VARYING(100) NOT NULL,
  BIRTHDAY DATE,
  CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID),
  CONSTRAINT UNIQ_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
  FILM_ID BIGINT NOT NULL,
  NAME CHARACTER VARYING(50) NOT NULL,
  CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID, NAME),
  CONSTRAINT FILM_GENRE_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID)
);

CREATE TABLE IF NOT EXISTS FILM_PERSON (
  FILM_ID BIGINT NOT NULL,
  PERSON_ID BIGINT NOT NULL,
  CONSTRAINT FILM_PERSON_PK PRIMARY KEY (FILM_ID, PERSON_ID),
  CONSTRAINT FILM_PERSON_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID),
  CONSTRAINT FILM_PERSON_PERSON_FK FOREIGN KEY (PERSON_ID) REFERENCES PUBLIC.PERSON(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS FRIEND (
  PERSON_ID BIGINT NOT NULL,
  FRIEND_ID BIGINT NOT NULL,
  STATUS_NAME CHARACTER VARYING(50),
  CONSTRAINT FRIEND_PK PRIMARY KEY (PERSON_ID, FRIEND_ID),
  CONSTRAINT FRIEND_PERSON_FK FOREIGN KEY (PERSON_ID) REFERENCES PUBLIC.PERSON(PERSON_ID),
  CONSTRAINT FRIEND_PERSON_FK_1 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.PERSON(PERSON_ID)
);
